title: Dr. Janelle Peters
description: 'Humanities Scholar, Professor, K-12 Educator'
social_link: Twitter
social_username: JanellePeters
github_repo: janellepeters
github_username: Janelle Peters
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /dr__janelle_peters
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
